-- ============================================================================
-- PIA 0013 -- TRANSLATE SERVER-SIDE MESSAGES TO ENGLISH
-- ============================================================================
-- These strings surface in the admin UI, in browser consoles, and in the audit
-- scripts, so they are operator-facing diagnostics.
--
-- Rather than retyping every function body (which risks silently changing
-- logic), this reads each function's own definition via pg_get_functiondef(),
-- substitutes only the message text, and re-executes it. Behaviour is
-- guaranteed identical -- only the strings differ.
--
-- It also picks up the admin_* wrappers generated by 0011, whose guard message
-- was written inline by that migration's DO block.
--
-- NOT TRANSLATED: the PIA agent's dialogue to students in
-- student/js/tutoring-dashboard.js. That is Filipino instructional content for
-- Grade 7 learners, not incidental hardcoding -- see the note in the summary.
-- ============================================================================

do $$
declare
  r     record;
  v_def text;
  v_new text;
  i     int;
  n     int := 0;
  v_map text[][] := array[
    array['PIA: walang authenticated session.',
          'PIA: no authenticated session.'],
    array['PIA: walang profile para sa session na ito.',
          'PIA: no profile found for this session.'],
    array['PIA: walang profile na %',
          'PIA: no profile found for %'],
    array['PIA: bawal ang direktang pagsulat sa protektadong profile column. Gamitin ang submit_ocean_results() / set_student_stage().',
          'PIA: direct writes to protected profile columns are not allowed. Use submit_ocean_results() / set_student_stage().'],
    array['PIA: hindi ka pwedeng gumawa ng profile row (role=%).',
          'PIA: you are not allowed to create a profile row (role=%).'],
    array['PIA: hindi ka pwedeng magbura ng profile row (role=%).',
          'PIA: you are not allowed to delete a profile row (role=%).'],
    array['PIA: hindi ka pwedeng magbago ng profile na hindi sa iyo.',
          'PIA: you are not allowed to modify a profile that is not yours.'],
    array['PIA: naisumite na ang OCEAN test mo. Humingi ng retake sa admin.',
          'PIA: your OCEAN test has already been submitted. Ask an admin for a retake.'],
    array['PIA: kailangan ng eksaktong 50 na sagot (natanggap: %).',
          'PIA: exactly 50 responses are required (received: %).'],
    array['PIA: bawat sagot ay dapat nasa 1..5.',
          'PIA: every response must be between 1 and 5.'],
    array['PIA: hindi kilalang stage: %',
          'PIA: unknown stage: %'],
    array['PIA: hindi kilalang stage key: %',
          'PIA: unknown stage key: %'],
    array['PIA: hindi kilalang problem_id: %',
          'PIA: unknown problem_id: %'],
    array['PIA: admin lang ang pwedeng magbukas/magsara ng stage.',
          'PIA: only an admin can open or close a stage.'],
    array['PIA: admin lang ang pwedeng mag-revoke ng device.',
          'PIA: only an admin can revoke a device.'],
    array['PIA: admin lang ang pwedeng tumawag ng',
          'PIA: only an admin may call'],
    array['PIA: kailangan ng device id.',
          'PIA: a device id is required.'],
    array[' device limit lang. Mag-sign out muna sa kabilang device.',
          ' device limit reached. Please sign out on your other device first.'],
    array['PIA: hindi pa naiseserve ang problemang ito.',
          'PIA: this problem has not been served yet.'],
    array['PIA: hindi pa tapos ang problemang ito.',
          'PIA: this problem is not finished yet.'],
    array['PIA: walang hint para sa problem na ito.',
          'PIA: there are no hints for this problem.']
  ];
begin
  for r in
    select p.oid, p.proname
      from pg_proc p join pg_namespace nsp on nsp.oid = p.pronamespace
     where nsp.nspname = 'public'
       and p.prokind = 'f'
       and pg_get_functiondef(p.oid) like '%PIA%'
  loop
    v_def := pg_get_functiondef(r.oid);
    v_new := v_def;

    for i in 1 .. array_length(v_map, 1) loop
      v_new := replace(v_new, v_map[i][1], v_map[i][2]);
    end loop;

    if v_new is distinct from v_def then
      execute v_new;
      n := n + 1;
    end if;
  end loop;

  raise notice 'PIA: translated messages in % function(s).', n;
end;
$$;

notify pgrst, 'reload schema';


-- Report: anything still holding a Tagalog message.
select p.proname as function_name,
       case when pg_get_functiondef(p.oid) ~ '(walang|hindi|bawal|kailangan|lamang|pwede|ang |ng )'
            then '*** still has Tagalog ***' else 'english' end as status
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
 where n.nspname = 'public'
   and p.prokind = 'f'
   and pg_get_functiondef(p.oid) like '%PIA%'
 order by status desc, p.proname;
