-- ============================================================================
-- PIA 0028 -- MATH TASK BANK (question_bank + app_config), ADMIN ONLY
-- ============================================================================
-- The admin console's new "Math Task" view manages sentence problems for
-- three topics -- EASY (finding a percentage), MEDIUM (percentage increase),
-- HARD (percentage decrease) -- each with a step-by-step breakdown and three
-- tiers of hints, plus the adaptive rules per topic. It was built by a team
-- member against their own Supabase project; these are its two tables,
-- created here with the SAME column names so rows exported from that project
-- import unchanged.
--
--   question_bank   one row per problem.
--     hint          TEXT holding JSON: {"defaultHint": "...", "steps": [
--                     {"prompt","answer","hint1","hint2","hint3"}, ...]}.
--                   Plain text from older rows is still accepted by the page.
--   app_config      exactly one row (id = 1): per-topic mastery threshold,
--                   questions to level up, wrong answers to level down, and
--                   one max_points for all topics.
--
-- ADMIN ONLY, READS INCLUDED. Every row carries its final answer and every
-- step answer. A student who could SELECT this table would have the answer
-- key -- the leak AUDIT_answer_key_reachability.sql exists to catch. So
-- students and teachers get no access at all, and anon is revoked. When the
-- tutoring page starts serving these problems, it must do so through a
-- SECURITY DEFINER function that returns the problem without its answers,
-- the way serve_problem() and check_math_answer() already work.
--
-- NOT YET WIRED TO STUDENTS. The tutoring dashboard still serves the
-- built-in algebra set (student/js/math-problems.js) and levels students up
-- with the server's own decision tree. Nothing saved here changes what a
-- student sees until that is built -- the console says so on the page.
--
-- SAFE TO RE-RUN: tables and columns are created only if missing, policies
-- are dropped and recreated, the config row is inserted only if absent.
-- ============================================================================

begin;

-- ---------------------------------------------------------------------------
-- PREFLIGHT
-- ---------------------------------------------------------------------------
do $$
begin
  if to_regprocedure('public.pia_caller_role()') is null
     or to_regprocedure('public.jwt_is_current()') is null then
    raise exception 'PIA 0028 ABORT (nothing changed): pia_caller_role() / jwt_is_current() are missing -- run 0001 and 0020-0022 first.'
      using errcode = 'P0001';
  end if;
end;
$$;


-- ---------------------------------------------------------------------------
-- 1. question_bank
-- ---------------------------------------------------------------------------
create table if not exists public.question_bank (
  id           bigint generated by default as identity primary key,
  difficulty   text        not null default 'EASY',
  question     text        not null default '',
  final_answer text        not null default '',
  hint         text,
  points       int         not null default 10,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- A table that already existed (made by hand) gets whatever it is missing.
alter table public.question_bank add column if not exists difficulty   text        not null default 'EASY';
alter table public.question_bank add column if not exists question     text        not null default '';
alter table public.question_bank add column if not exists final_answer text        not null default '';
alter table public.question_bank add column if not exists hint         text;
alter table public.question_bank add column if not exists points       int         not null default 10;
alter table public.question_bank add column if not exists created_at   timestamptz not null default now();
alter table public.question_bank add column if not exists updated_at   timestamptz not null default now();

-- The page validates these too; the database is what holds them. NOT VALID
-- keeps an existing table's odd rows from blocking the migration while every
-- new or edited row is still checked.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'question_bank_difficulty_check') then
    alter table public.question_bank add constraint question_bank_difficulty_check
      check (difficulty in ('EASY', 'MEDIUM', 'HARD')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'question_bank_points_check') then
    alter table public.question_bank add constraint question_bank_points_check
      check (points between 1 and 500) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'question_bank_text_len_check') then
    alter table public.question_bank add constraint question_bank_text_len_check
      check (length(question) <= 2000 and length(final_answer) <= 200
             and length(coalesce(hint, '')) <= 20000) not valid;
  end if;
end;
$$;

create index if not exists question_bank_difficulty_idx on public.question_bank (difficulty, id);

create or replace function public.pia_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists question_bank_touch on public.question_bank;
create trigger question_bank_touch
  before update on public.question_bank
  for each row execute function public.pia_touch_updated_at();


-- ---------------------------------------------------------------------------
-- 2. app_config -- one row
-- ---------------------------------------------------------------------------
create table if not exists public.app_config (
  id                   int primary key default 1,
  easy_mastery         int not null default 80,
  easy_max_errors      int not null default 3,
  easy_min_questions   int not null default 3,
  medium_mastery       int not null default 80,
  medium_max_errors    int not null default 3,
  medium_min_questions int not null default 3,
  hard_mastery         int not null default 80,
  hard_max_errors      int not null default 3,
  hard_min_questions   int not null default 3,
  max_points           int not null default 10,
  updated_at           timestamptz not null default now()
);

alter table public.app_config add column if not exists easy_mastery         int not null default 80;
alter table public.app_config add column if not exists easy_max_errors      int not null default 3;
alter table public.app_config add column if not exists easy_min_questions   int not null default 3;
alter table public.app_config add column if not exists medium_mastery       int not null default 80;
alter table public.app_config add column if not exists medium_max_errors    int not null default 3;
alter table public.app_config add column if not exists medium_min_questions int not null default 3;
alter table public.app_config add column if not exists hard_mastery         int not null default 80;
alter table public.app_config add column if not exists hard_max_errors      int not null default 3;
alter table public.app_config add column if not exists hard_min_questions   int not null default 3;
alter table public.app_config add column if not exists max_points           int not null default 10;
alter table public.app_config add column if not exists updated_at           timestamptz not null default now();

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'app_config_single_row') then
    alter table public.app_config add constraint app_config_single_row check (id = 1) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'app_config_ranges') then
    alter table public.app_config add constraint app_config_ranges check (
      easy_mastery   between 50 and 100 and medium_mastery   between 50 and 100 and hard_mastery   between 50 and 100
      and easy_max_errors    between 1 and 10 and medium_max_errors    between 1 and 10 and hard_max_errors    between 1 and 10
      and easy_min_questions between 1 and 10 and medium_min_questions between 1 and 10 and hard_min_questions between 1 and 10
      and max_points between 1 and 500
    ) not valid;
  end if;
end;
$$;

drop trigger if exists app_config_touch on public.app_config;
create trigger app_config_touch
  before update on public.app_config
  for each row execute function public.pia_touch_updated_at();

insert into public.app_config (id) values (1) on conflict (id) do nothing;


-- ---------------------------------------------------------------------------
-- 3. Access: admins only, for reading as well as writing.
-- ---------------------------------------------------------------------------
alter table public.question_bank enable row level security;
alter table public.app_config    enable row level security;

-- Anything else a hand-made table may have carried goes first.
do $$
declare r record;
begin
  for r in
    select schemaname, tablename, policyname
      from pg_policies
     where schemaname = 'public' and tablename in ('question_bank', 'app_config')
  loop
    execute format('drop policy %I on %I.%I', r.policyname, r.schemaname, r.tablename);
  end loop;
end;
$$;

create policy question_bank_admin_all on public.question_bank
  for all to authenticated
  using      (public.pia_caller_role() = 'admin' and public.jwt_is_current())
  with check (public.pia_caller_role() = 'admin' and public.jwt_is_current());

create policy app_config_admin_all on public.app_config
  for all to authenticated
  using      (public.pia_caller_role() = 'admin' and public.jwt_is_current())
  with check (public.pia_caller_role() = 'admin' and public.jwt_is_current());

revoke all on public.question_bank from public, anon, authenticated;
revoke all on public.app_config    from public, anon, authenticated;
grant select, insert, update, delete on public.question_bank to authenticated;
grant select, insert, update         on public.app_config    to authenticated;

-- The id sequence, whatever it is called (identity or a hand-made serial).
do $$
declare v_seq text := pg_get_serial_sequence('public.question_bank', 'id');
begin
  if v_seq is not null then
    execute format('grant usage on sequence %s to authenticated', v_seq);
  end if;
end;
$$;


-- ---------------------------------------------------------------------------
-- POSTFLIGHT -- a real student and a real admin, under RLS. Rolled back.
-- ---------------------------------------------------------------------------
do $$
declare
  v_student text;
  v_admin   text;
  v_iat     bigint := extract(epoch from clock_timestamp())::bigint + 1;
  v_rows    int;
begin
  if has_table_privilege('anon', 'public.question_bank', 'SELECT') then
    raise exception 'PIA 0028 ABORT: anon can read question_bank.' using errcode = 'P0001';
  end if;

  select email into v_student from public.profiles
   where lower(trim(coalesce(role, 'student'))) = 'student' order by email limit 1;
  select email into v_admin from public.profiles
   where lower(trim(role)) = 'admin' order by email limit 1;

  -- (a) A student sees no question and no config, and cannot write either.
  if v_student is not null then
    begin
      insert into public.question_bank (difficulty, question, final_answer, points)
      values ('EASY', 'pia-0028-probe', '42', 10);

      perform set_config('request.jwt.claims', json_build_object(
        'email', v_student, 'role', 'authenticated', 'iat', v_iat)::text, true);
      execute 'set local role authenticated';

      select count(*) into v_rows from public.question_bank;
      if v_rows > 0 then
        raise exception 'PIA 0028 ABORT: a student can read the question bank (answers included). Rolling back.'
          using errcode = 'P0001';
      end if;
      select count(*) into v_rows from public.app_config;
      if v_rows > 0 then
        raise exception 'PIA 0028 ABORT: a student can read app_config. Rolling back.' using errcode = 'P0001';
      end if;

      begin
        insert into public.question_bank (difficulty, question, final_answer, points)
        values ('EASY', 'pia-0028-student-write', '1', 10);
        raise exception 'PIA 0028 ABORT: a student can add questions. Rolling back.' using errcode = 'P0001';
      exception when insufficient_privilege then
        null;   -- refused by RLS, as it should be
      end;

      execute 'reset role';
      raise exception 'probe done' using errcode = 'P0002';
    exception
      when sqlstate 'P0002' then
        raise notice 'PIA 0028 OK: a student can neither read nor write the question bank or the config.';
    end;
  else
    raise notice 'PIA 0028: no student profile to probe with -- skipped.';
  end if;

  -- (b) An admin can add, read, change and delete.
  if v_admin is not null then
    begin
      perform set_config('request.jwt.claims', json_build_object(
        'email', v_admin, 'role', 'authenticated', 'iat', v_iat)::text, true);
      execute 'set local role authenticated';

      insert into public.question_bank (difficulty, question, final_answer, points)
      values ('HARD', 'pia-0028-admin-probe', '25%', 10);
      update public.question_bank set points = 20 where question = 'pia-0028-admin-probe';
      get diagnostics v_rows = row_count;
      if v_rows <> 1 then
        raise exception 'PIA 0028 ABORT: an admin cannot edit questions. Rolling back.' using errcode = 'P0001';
      end if;
      update public.app_config set max_points = 12 where id = 1;
      get diagnostics v_rows = row_count;
      if v_rows <> 1 then
        raise exception 'PIA 0028 ABORT: an admin cannot save the config. Rolling back.' using errcode = 'P0001';
      end if;
      delete from public.question_bank where question = 'pia-0028-admin-probe';

      execute 'reset role';
      raise exception 'probe done' using errcode = 'P0002';
    exception
      when sqlstate 'P0002' then
        raise notice 'PIA 0028 OK: an admin can add, edit and delete questions and save the config.';
    end;
  else
    raise notice 'PIA 0028: no admin profile to probe with -- skipped.';
  end if;

  perform set_config('request.jwt.claims', '', true);
end;
$$;

commit;

notify pgrst, 'reload schema';


-- Report
select 'question_bank' as "table", count(*) as rows from public.question_bank
union all
select 'app_config', count(*) from public.app_config;
